//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 05:00:27 PM GMT 
//

package ie.gmit.sw.Model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Customer", namespace = "http://sw.gmit.ie/Model/", propOrder = { "customerId", "firstName", "lastName",
		"age", "county", "dateOfBirth" })
public class Customer {

	@XmlElement(namespace = "http://sw.gmit.ie/Model/")
	protected int customerId;
	@XmlElement(namespace = "http://sw.gmit.ie/Model/", required = true)
	protected String firstName;
	@XmlElement(namespace = "http://sw.gmit.ie/Model/", required = true)
	protected String lastName;
	@XmlElement(namespace = "http://sw.gmit.ie/Model/")
	protected int age;
	@XmlElement(namespace = "http://sw.gmit.ie/Model/", required = true)
	protected String county;
	@XmlElement(namespace = "http://sw.gmit.ie/Model/", required = true)
	protected String dateOfBirth;

	public int getCustomerId() {
		return customerId;
	}

	public void setCustomerId(int value) {
		this.customerId = value;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String value) {
		this.firstName = value;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String value) {
		this.lastName = value;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int value) {
		this.age = value;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String value) {
		this.county = value;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String value) {
		this.dateOfBirth = value;
	}

}
