//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 05:00:27 PM GMT 
//

package ie.gmit.sw.Model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the ie.gmit.sw.dsmodels package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Comment_QNAME = new QName("http://sw.gmit.ie/Model/", "comment");
	private final static QName _Booking_QNAME = new QName("http://sw.gmit.ie/Model/", "booking");

	public ObjectFactory() {
	}

	public Booking createBooking() {
		return new Booking();
	}

	public Vehicle createVehicle() {
		return new Vehicle();
	}

	public Customer createCustomer() {
		return new Customer();
	}

	@XmlElementDecl(namespace = "http://sw.gmit.ie/Model/", name = "comment")
	public JAXBElement<String> createComment(String value) {
		return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
	}

	@XmlElementDecl(namespace = "http://sw.gmit.ie/Model/", name = "booking")
	public JAXBElement<Booking> createBooking(Booking value) {
		return new JAXBElement<Booking>(_Booking_QNAME, Booking.class, null, value);
	}

}
